### ISSUE TITLE
Install fails - due to drupal/coder

### ISSUE THREAD

**Issue by anschinsan** [drupal-composer/drupal-composer-project#383]
Hi,
for the last few days I tried to install drupal8 with the following command:
`composer create-project drupal-composer/drupal-project:8.x-dev drupal8 --stability dev --no-interaction`

It always worked well - until today in the morning (12 hours ago). Now install fails on my vagrant box with following error:
```
 default:   - Installing drupal/coder (8.2.12): 
default: Cloning 984c54a7b1
 default:                                                                                                                                                                                                                                                                                       
default:   [RuntimeException]                                                                                                                                                                                                                                                                  
default:   Failed to execute git clone --no-checkout 'https://git.drupal.org/project/coder.git' '/var/www/public/drupal8/vendor/drupal/coder' && cd '/var/www/public/drupal8/vendor/drupal/coder' && git remote add composer 'https://git.drupal.org/project/coder.git' && git fetch composer  
 default:                                                                                                                                                                                                                                                                                       
default:   Cloning into '/var/www/public/drupal8/vendor/drupal/coder'...                                                                                                                                                                                                                       
default:   fatal: fsync error on '/var/www/public/drupal8/vendor/drupal/coder/.git/objects/pack/tmp_idx_NSmq0g': Permission denied                                                                                                                                                             
default:   fatal: index-pack failed
```

Unfortunately I'm no expert in using composer. I noticed, I can install drupal when using
`composer install --no-dev`
but I'd like to install dev modules as I want to setup a new site which will need custom modules I'll have to write ...

My questions are:
Is this my fault or is something wrong in drupal/coder ? /var/www/public/drupal8/vendor/drupal/coder is not created ...

What do I have to do to install the project the recommended way when the install fails to one rather small problem. drupal/coder is not mentioned in the composer.json file but only in composer.lock. I tried to edit this file - but with no result.

Please, give me some hints about the next steps I could or should try ...
Thx, anschinsan
